### ISSUE TITLE
Clams spawn waaaaaaaay too much

### ISSUE THREAD

**Issue by Sunconure11** [mc-jt9/ProjectVibrantJourneys#54] opened 2019-02-21 20:30 UTC
![screenshot 2019-02-21 15 29 37](https://user-images.githubusercontent.com/5614902/53199645-9e3f9880-35ed-11e9-8071-e489a1fc4fa9.png)

**Comment by WenXin20** [comment] 2019-02-21 21:32
I have this happening too.

**Comment by mc-jt9** [comment] 2019-02-22 02:40
That's so weird that I don't see that when I do testing. I'll see how I can tone it down. I've been busy lately which is why the mod hasn't been worked on since the last update.

**Comment by ate0ate** [comment] 2019-02-22 05:26
Its pretty strange in my SSP world as it doesn't seem consistent. I had few clams in some areas, especially as I was exploring and looking for a place to settle. Once I did settle in somewhere and start expanding I noticed quite a few clams, though not as many as in the pic, were spawning in a small pond I had dug out. I am near a swamp/river though which has become quite infested with clams now. They reappear just as fast as I can kill them too lol. Got two stack of clams in less than a minute pretty easily:)

**Comment by ate0ate** [comment] 2019-02-23 22:42
As a side note, squids are not spawning at all regardless of the "restrict to oceans" flag and I assume its due of the clam crowding them out of the spawn queue. More importantly the config for clam spawn weight has no effect. Unfortunately even trying to disable them outright by setting the weight to zero results in them continuing to spawn like crazy.

**Comment by SwordShaman** [comment] 2019-02-24 17:26
I've had this issue as well.  It's caused my server to slow to a crawl.  Disabling their spawn doesn't remove clam entities that have already filled the bottom of my waterways, so I'd like to use the kill command to get rid of them.  How would I do that?  I've tried the following with no success.
/kill @e[type=Clam]
/kill @e[type=EntityClam]
/kill @e[type=pvj:Clam]
/kill @e[type=pvj:EntityClam]

**Comment by ate0ate** [comment] 2019-02-24 18:07
I noticed this as well. My world was having some insane lag. Couldn't get animals to breed or respond to right clicking at times due to the slow down. Same with crops. I also could not get the Clams to stop spawning despite actually going into the source and removing the addSpawn. I finally resorted to making a build that removes the Clam Entity completely, but kept the items lol, and that works great. I was actually shocked by the improvement. I have been having issues with lag/slowdown for a while now and couldn't find the culprit. Finally did! I'll post a link to the build here but be forewarned, I am no coder. I simply went through the commits on Github here since Clams were added and removed all the code related to the clam Entity. 
http://www.mediafire.com/file/1ssz64lz31obvdy/ProjectVibrantJourneys-1.12.2-1.6.0_Mollusk_Free_Edition.jar/file

**Comment by WenXin20** [comment] 2019-02-25 02:27
Starfishes also seem to spawn a lot, though not as much as the clams.
@SwordShaman I believe the command to kill the clams is `/kill @e[type=pvj:pvj_clam]`.

**Comment by ate0ate** [comment] 2019-02-25 02:55
Do you know if the starfishes are responding to the config settings by chance? I turned them down while trying to figure out the clam situation and haven't noticed anything off, but I can't say I've done any testing.

**Comment by WenXin20** [comment] 2019-02-25 04:48
I don't know, I haven't had the time to test that.

**Comment by dannydjdk** [comment] 2019-02-28 15:03
It appears that the problem is that they continue to spawn regardless of how many are currently in the area. I turned the spawning in the configs down to about 1/10th the default. At first, I thought this fixed the problem. Squids were spawning again, but eventually, the clams took over.
This might explain why it didn't come up in testing. You have to hang around an area for a while before the issue surfaces.

**Comment by Murdockzor** [comment] 2019-04-03 19:38
![clams](https://user-images.githubusercontent.com/49251619/55507784-d5628a00-562e-11e9-972a-2a68bccd5291.png)

**Comment by mc-jt9** [comment] 2019-04-05 03:42
Hopefully fixed in 1.6.1 - they should also be able to despawn.

**Closed by mc-jt9** 2019-04-05 03:42 UTC

**Comment by mc-jt9** [comment] 2019-04-05 03:44
Oh also don't forget to delete your config so the game loads a new one with the corrected values.
